name: primeira-pipeline
on:  # Trigger
  push:
    branches: ["developer"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Minha Segunda Ação"
        run: |
          echo "Você criou o seu primeiro Workflow"
          echo "Parabéns !!!"
  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
      - name: "Definição da versão 20.13.1 do NodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'
      - name: "Verificação da versão do NodeJS após Atualiado"
        run: node --version
    
