name: primeira-pipeline
on:  # Trigger
  push:
    branches: ["developer"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Minha Segunda Ação"
        run: |
          echo "Você criou o seu primeiro Workflow"
          echo "Parabéns !!!"
  segundo-job:
    name: "Instalação do ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
    
