name: primeira-pipeline
on:  # Trigger
  push:
    branches: ["developer"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Segunda Ação"
        run: |
          echo "Você criou o seu primeiro Workflow"
          echo "Parabéns !!!"
        
      
    
